name: Flutter Builder
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "12.x"
          distribution: 'zulu'

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: subosito/flutter-action@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "12.x"
          distribution: 'zulu'

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test
      - run: flutter build ios --release --no-codesign

  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: "12.x"
          distribution: 'zulu'

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle

  build_web:
    name: Build Flutter (Web)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: "12.x"
          distribution: 'zulu'

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web

  build_windows:
    name: Build Flutter (Windows)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: "12.x"
          distribution: 'zulu'

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter test
      - run: flutter build windows

  build_linux:
    name: Build Flutter (Linux)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: "12.x"
          distribution: 'zulu'

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: sudo apt-get update -y && sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter test
      - run: flutter build linux

  build_macos:
    name: Build Flutter (MacOS)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: "12.x"
          distribution: 'zulu'

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
      - run: flutter test
      - run: flutter build macos

