name: Flutter Builder
on: [push]



jobs:
  list_files:
      name: List files
      runs-on: ubuntu-latest
      steps:
        - uses: subosito/flutter-action@v2
        - uses: actions/setup-java@v2
          with:
            java-version: "12.x"
            distribution: 'zulu'

        - uses: subosito/flutter-action@v2
          with:
            channel: "stable"
        - run: ls -la
        - run: pwd
        - run: cd ../ && ls -la && pwd
        