name: Flutter CI

# This workflow is triggered on pushes to the repository.

on: [push]
    
# on: push    # Default will running for every branch.
    
jobs:
  flutter_test:
    name: Run Flutter Test and Analyze it
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2
        with:
            channel: "stable"
      - uses: actions/setup-java@v2
        with:
            java-version: "12.x"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test