name: Flutter CI
on: [push]

jobs:
  flutter_test:
    name: Flutter Tester/Linter/Analyzer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter format --set-exit-if-changed .
    - run: flutter analyze .
    - run: flutter test

  flutter_android_build:
    name: Flutter Build (Android)
    runs-on: ubuntu-latest
    needs: [flutter_test]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk

  flutter_ios_build:
    name: Flutter Build (iOS)
    runs-on: macos-latest
    needs: [flutter_test]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
        architecture: x64
    - run: flutter pub get
    - run: flutter test
    - run: flutter build ios --release --no-codesign
    - uses: actions/upload-artifact@v1
      with:
        name: release-ios
        path: build/ios/iphoneos/Runner.app
  
  flutter_web_build:
    name: Flutter Build (Web)
    runs-on: ubuntu-latest
    needs: [flutter_test]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build web
    - uses: actions/upload-artifact@v1
      with:
        name: release-web
        path: build/web/web

  flutter_linux_build:
    name: Flutter Build (Linux)
    runs-on: ubuntu-latest
    needs: [flutter_test]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run:  sudo apt-get update -y && sudo apt-get install -y ninja-build libgtk-3-dev
    - run: flutter config --enable-linux-desktop
    - run: flutter pub get
    - run: flutter test
    - run: flutter build linux
    - uses: actions/upload-artifact@v1
      with:
        name: release-linux
        path: build/linux/outputs/flutter-linux-*/flutter
    
  flutter_windows_build:
    name: Flutter Build (Windows)
    runs-on: windows-latest
    needs: [flutter_test]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter config --enable-windows-desktop
    - run: flutter pub get
    - run: flutter test
    - run: flutter build windows
    - uses: actions/upload-artifact@v1
      with:
        name: release-windows
        path: build/windows/outputs/Flutter.exe

  flutter_macos_build:
    name: Flutter Build (macOS)
    runs-on: macos-latest
    needs: [flutter_test]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter config --enable-mac-desktop
    - run: flutter pub get
    - run: flutter test
    - run: flutter build macos
    - uses: actions/upload-artifact@v1
      with:
        name: release-macos
        path: build/macos/Flutter.app